update nd    Commit created manually or by external script    On commit
Status
    init
    retrieve       1991 retrieved     28 to prepare manually, 30 to deduplicate [1991 quality-curated]
    prescreen      1898 included      93 to prescreen      [116 prescreen excluded]
    pdfs           1782 retrieved
    screen         1782 included
    data           1780 synthesized   2 to synthesize

Software
    colrev                         version 0.13.2
    Python                         version 3.12.3
    Git                            version 2.48.1
    Docker                         version 27.5.1, build 9f9e405

diff --git a/.github/workflows/colrev_update.yml b/.github/workflows/colrev_update.yml
--- a/.github/workflows/colrev_update.yml
+++ b/.github/workflows/colrev_update.yml
@@ -22,15 +22,12 @@ jobs:
           git checkout uv
           pip install uv
           uv venv && uv pip install .
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
-          which colrev
-          colrev --version
 
-      - name: Activate virtual environment and verify colrev
+      - name: Ensure colrev is available
         run: |
-          source .venv/bin/activate
-          which colrev
-          colrev --version
+          export PATH="$HOME/.local/bin:$PATH"
+          which colrev || echo "colrev not found"
+          colrev --version || echo "colrev failed to run"
 
       - name: Add colrev to PATH
         run: echo "$HOME/.local/bin" >> $GITHUB_PATH
