udpate nd    Commit created manually or by external script    On commit
Status
    init
    retrieve       1991 retrieved     28 to prepare manually, 30 to deduplicate [1991 quality-curated]
    prescreen      1898 included      93 to prescreen      [116 prescreen excluded]
    pdfs           1782 retrieved
    screen         1782 included
    data           1780 synthesized   2 to synthesize

Software
    colrev                         version 0.13.2
    Python                         version 3.12.3
    Git                            version 2.48.1
    Docker                         version 27.5.1, build 9f9e405

diff --git a/.github/workflows/colrev_update.yml b/.github/workflows/colrev_update.yml
--- a/.github/workflows/colrev_update.yml
+++ b/.github/workflows/colrev_update.yml
@@ -30,10 +30,7 @@ jobs:
           export PATH="$PWD/.venv/bin:$PATH"
           echo "Checking colrev installation..."
           which colrev || echo "colrev not found"
-          colrev --version || echo "colrev failed to run"
-
-      - name: Add colrev to PATH
-        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
+          colrev version || echo "colrev failed to run"
 
       - name: Setup git
         run: |
@@ -50,6 +47,7 @@ jobs:
       - name: Run CoLRev update
         working-directory: ${{ runner.temp }}/colrev
         run: |
+          source .venv/bin/activate
           colrev install .
           colrev search -f
           colrev load
